### ISSUE TITLE
Syntax for input and output audio devices

### ISSUE THREAD

**Issue by Montilien** [xssfox/mumblerf#1]
Hi,
With aplay and arecord command line I find my audio USB device as CARD=3 Device=0.
I cannot find the good syntax to fullfill In INPUT_DEVICE and OUTPUT_DEVICE.
Canyou help me?
Regards
André - F1FHK

**Comment by xssfox** [comment]
Use --list-audio-devices

**Comment by Montilien** [comment]
Hi,
--list-audio-devices gave me:
Input devices:
  1 - ahubhdmi: ahub_plat-i2s-hifi i2s-hifi-0 (hw:2,0)
  2 - C-Media USB Headphone Set: Audio (hw:3,0)
Output devices:
  0 - audiocodec: CDC PCM Codec-0 (hw:0,0)
  1 - ahubhdmi: ahub_plat-i2s-hifi i2s-hifi-0 (hw:2,0)
  2 - C-Media USB Headphone Set: Audio (hw:3,0)
  3 - sysdefault
  4 - default
  5 - dmix

And when I launch mumbleRF with:

python3.11 mumblerf.py --input-device C-Media USB Headphone Set: Audio (hw:3,0) --output-device C-Media USB Headphone Set: Audio (hw:3,0) --report-level --serial-port /dev/ttyUSB0 --vox-level 100 --audio-out-multiplier 0.5

I get this error message:

-bash: syntax error near unexpected token `('

Nota: All commands are sent inside putty Console.

A question:
Is it possible to declare input and output device by default in mumblerf.py directly ?

thanks for your help

Rgards - F1FHK

**Comment by xssfox** [comment]
You can use quotes around the band if the sound device or use the number on the left instead of the name
